{% set name = "sagemaker-jupyterlab-extension-common" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sagemaker-jupyterlab-extension-common-{{ version }}.tar.gz
  sha256: 40256cd715a5fa684eac3c9a50a6fe61afabdf383e119c40bacde70c517963dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - jupyter_packaging >=0.12.0,<0.13.dev0
    - setuptools >=40.8.0
    - wheel
    - urllib3 <2
    - jupyterlab >4
    - pip
  run:
    - python >=3.9
    - jupyterlab >=4
    - jupyter_events >=0.6.0
    - aiobotocore >=2.7.0
    - aws-embedded-metrics

test:
  imports:
    - sagemaker_jupyterlab_extension_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker/
  summary: SageMaker JupyterLab workspace common module
  license: LicenseRef-.amazon.com.-AmznSL-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zuoyuanh
